# 1. Usiamo FastSurfer CPU come fondamenta
FROM deepmi/fastsurfer:cpu-v2.4.2

USER root

ENV DEBIAN_FRONTEND=noninteractive

# 2. Installiamo SOLO Java (per Nextflow) e Python (per FastAPI e PyRadiomics)
RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    curl \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# 3. Installiamo Nextflow
RUN curl -s https://get.nextflow.io | bash \
    && mv nextflow /usr/local/bin/ \
    && chmod +x /usr/local/bin/nextflow

# 4. Installiamo le librerie Python
RUN pip3 install --no-cache-dir fastapi uvicorn pydantic httpx pyradiomics

# 5. Setup dell'ambiente di lavoro
WORKDIR /app
COPY . /app

EXPOSE 8002

ENTRYPOINT []

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]