site_name: ClinicalTwin FTD Pipeline Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Pipeline: pipeline.md
  - Installation: installation.md
  - Usage: usage.md
  - Testing: testing.md
  - Dataset: dataset.md